"""initial

Revision ID: 44c5074aeb41
Revises: 
Create Date: 2026-03-31 10:24:42.204614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '44c5074aeb41'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('branches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('sync_cursor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_synced_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('last_record_id', sa.Text(), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sync_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('finished_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('total_received', sa.Integer(), nullable=True),
    sa.Column('total_mapped', sa.Integer(), nullable=True),
    sa.Column('total_unmapped', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('branch_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('key_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('key_value', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_type', 'key_value', name='uq_branch_mappings_key')
    )
    op.create_index('ix_branch_mappings_key', 'branch_mappings', ['key_type', 'key_value'], unique=False)
    op.create_table('segments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tinh_thanh', sa.VARCHAR(length=100), nullable=True),
    sa.Column('xa_phuong', sa.Text(), nullable=True),
    sa.Column('ten_duong', sa.Text(), nullable=True),
    sa.Column('doan', sa.Text(), nullable=True),
    sa.Column('doan_key', sa.Text(), nullable=True),
    sa.Column('tinh_thanh_norm', sa.Text(), nullable=True),
    sa.Column('xa_phuong_norm', sa.Text(), nullable=True),
    sa.Column('ten_duong_norm', sa.Text(), nullable=True),
    sa.Column('doan_key_norm', sa.Text(), nullable=True),
    sa.Column('vt1', sa.BigInteger(), nullable=True),
    sa.Column('vt2', sa.BigInteger(), nullable=True),
    sa.Column('vt3', sa.BigInteger(), nullable=True),
    sa.Column('vt4', sa.BigInteger(), nullable=True),
    sa.Column('nhom', sa.CHAR(length=1), nullable=True),
    sa.Column('nhom_manual', sa.Boolean(), nullable=False),
    sa.Column('so_can_vt1', sa.Integer(), nullable=True),
    sa.Column('so_can_vt2', sa.Integer(), nullable=True),
    sa.Column('so_can_vt3', sa.Integer(), nullable=True),
    sa.Column('so_can_vt4', sa.Integer(), nullable=True),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('trang_thai', sa.VARCHAR(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tinh_thanh_norm', 'xa_phuong_norm', 'ten_duong_norm', 'doan_key_norm', name='uq_segments_norm_key')
    )
    op.create_index('ix_segments_active', 'segments', ['is_active'], unique=False)
    op.create_index('ix_segments_nhom', 'segments', ['nhom'], unique=False)
    op.create_index('ix_segments_norm', 'segments', ['tinh_thanh_norm', 'xa_phuong_norm', 'ten_duong_norm', 'doan_key_norm'], unique=False)
    op.create_table('unmapped_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_record_id', sa.Text(), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('sync_log_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sync_log_id'], ['sync_log.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_unmapped_resolved', 'unmapped_records', ['resolved'], unique=False)
    op.create_table('assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('segment_id', sa.Integer(), nullable=False),
    sa.Column('phu_trach', sa.Text(), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('imported_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['segment_id'], ['segments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('segment_id')
    )
    op.create_table('collected_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_record_id', sa.Text(), nullable=False),
    sa.Column('segment_id', sa.Integer(), nullable=True),
    sa.Column('vi_tri', sa.SmallInteger(), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('first_seen_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('last_synced_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('sync_log_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['segment_id'], ['segments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sync_log_id'], ['sync_log.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_record_id')
    )
    op.create_index('ix_collected_first_seen', 'collected_records', ['first_seen_at'], unique=False)
    op.create_index('ix_collected_segment_vitri', 'collected_records', ['segment_id', 'vi_tri'], unique=False)
    op.create_index('ix_collected_source_id', 'collected_records', ['source_record_id'], unique=False)
    op.create_table('verification_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('segment_id', sa.Integer(), nullable=False),
    sa.Column('nguoi_kiem_tra', sa.Text(), nullable=True),
    sa.Column('ket_qua', sa.Text(), nullable=True),
    sa.Column('verified_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['segment_id'], ['segments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('verification_log')
    op.drop_index('ix_collected_source_id', table_name='collected_records')
    op.drop_index('ix_collected_segment_vitri', table_name='collected_records')
    op.drop_index('ix_collected_first_seen', table_name='collected_records')
    op.drop_table('collected_records')
    op.drop_table('assignments')
    op.drop_index('ix_unmapped_resolved', table_name='unmapped_records')
    op.drop_table('unmapped_records')
    op.drop_index('ix_segments_norm', table_name='segments')
    op.drop_index('ix_segments_nhom', table_name='segments')
    op.drop_index('ix_segments_active', table_name='segments')
    op.drop_table('segments')
    op.drop_index('ix_branch_mappings_key', table_name='branch_mappings')
    op.drop_table('branch_mappings')
    op.drop_table('sync_log')
    op.drop_table('sync_cursor')
    op.drop_table('branches')
    # ### end Alembic commands ###
