"""add_loai_kiem_tra_to_verification_log

Revision ID: d17c55fb0d71
Revises: 44c5074aeb41
Create Date: 2026-04-02 15:46:58.831958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd17c55fb0d71'
down_revision: Union[str, None] = '44c5074aeb41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verification_log', sa.Column('loai_kiem_tra', sa.VARCHAR(length=10), server_default='auto', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('verification_log', 'loai_kiem_tra')
    # ### end Alembic commands ###
